services:
  postgres:
    container_name: datingtrap
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser  # Default user (change if necessary)
      POSTGRES_PASSWORD: Hanoi_1234  # Default password (change if necessary)
      POSTGRES_DB: datingtrap  # Database name
      PGDATA: /var/lib/postgresql/data  # Path to store data
    volumes:
      - datingtrap-db-data:/var/lib/postgresql/data  # Mount volume for data persistence
    ports:
      - "5432:5432"  # Make sure this is correct based on your intention

volumes:
  datingtrap-db-data:
