services:
  postgres:
    container_name: datingtrap
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser  # Default user (change if necessary)
      POSTGRES_PASSWORD: Hanoi_1234  # Default password (change if necessary)
      POSTGRES_DB: datingtrap  # Database name
      PGDATA: /var/lib/postgresql/data  # Path to store data
    volumes:
      - datingtrap-db-data:/var/lib/postgresql/data  # Mount volume for data persistence
    ports:
      - "5432:5432"  # Make sure this is correct based on your intention

  backend:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/datingtrap
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: Hanoi_1234

volumes:
  datingtrap-db-data: