spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/datingtrap
    username: myuser
    password: Hanoi_1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Nếu bạn dùng Hibernate để log SQL ra console:
  show-sql: true
  sql:
    init:
      mode: always
